apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-kv
  namespace: praveen-ns
spec:
  provider: azure
  secretObjects:
  - secretName: fitness-secret
    type: Opaque
    data:
    - objectName: mongodb-uri
      key: MONGODB_URI
    - objectName: port
      key: PORT
    - objectName: host
      key: HOST
    - objectName: node-env
      key: NODE_ENV

  parameters:
    usePodIdentity: "false"
    keyvaultName: "praveen-kv1"
    tenantId: "5989c502-2330-4d91-b86c-78a102728614"
    objects: |
      array:
        - |
          objectName: mongodb-uri
          objectType: secret
        - |
          objectName: port
          objectType: secret
        - |
          objectName: host
          objectType: secret
        - |
          objectName: node-env
          objectType: secret
